### PR TITLE
Update openturns-object inventory

### PR DESCRIPTION
**Pull request by sofianehaddad**
using 1.13rc inventory

### CODE REVIEW

**Comment by sofianehaddad** [comment]
@jschueller I close the PR
I think we should use the latest one

**Comment by jschueller** [comment]
Did I forget to merge it ?

**Comment by sofianehaddad** [comment]
yes :-)

**Comment by jschueller** [comment]
I guess I need some sleep then...

**Comment by jschueller** [comment]
see master

**Pull request closed without merging**
