### PR TITLE
Use intersphinx to link to ot doc

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by sofianehaddad** [comment]
+1

**Comment by sofianehaddad** [comment]
Finally I'm not sure about the issue (proxy check make compilation fails)

**Comment by jschueller** [comment]
@sofianehaddad, maybe we could provide a cache file python-inv.txt in the sources ?
http://www.sphinx-doc.org/en/stable/ext/intersphinx.html

**Comment by sofianehaddad** [comment]
yes good idea

**Comment by jschueller** [comment]
@sofianehaddad, but it's tied to sphinx >= 1.3

**Pull request merged**
