### PR TITLE
Add docstring test

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by sofianehaddad** [comment]
Could we add some routines to customize for python/doc/index.rst?

**Comment by jschueller** [comment]
@sofianehaddad, the thing is title underline depends on module name size, so it's complicated

**Comment by sofianehaddad** [comment]
@jschueller yes I know about underline but I thought that there is a "simple" hack.

**Comment by sofianehaddad** [comment]
I think that (one day) customize.sh should be moved into a python script ( for windows developers )

**Pull request merged**
